package com.application.view.panels.consultation.patient.dialog;

import com.application.interfaces.IConsultationPatientsDialog;
import com.application.model.dto.PatientDTO;
import java.awt.Component;
import java.awt.Frame;
import java.util.List;
import javax.swing.JOptionPane;

public class ConsultationPatientsDialog extends javax.swing.JDialog {
    private final IConsultationPatientsDialog listener;
    
    private boolean operationSuccess = false;
    
    /**
     * Creates new form ConsultationPatientsDialog
     * @param parent
     * @param listener
     * @param modal
     */
    public ConsultationPatientsDialog(java.awt.Frame parent, IConsultationPatientsDialog listener, boolean modal) {
        super(parent, modal);
        initComponents();
        this.listener = listener;
        loadPatientsData();
        
        if(comboBoxPatients.getSelectedItems().isEmpty()) {
            jButtonAddPatients.setEnabled(false);
        }
                
        setLocationRelativeTo(null);
        
        comboBoxPatients.addPropertyChangeListener("selectionChanged", evt -> {
            boolean hasSelection = !comboBoxPatients.getSelectedItems().isEmpty();
            jButtonAddPatients.setEnabled(hasSelection);
        });
         
    }
        
    /**  
     * Carga los datos de los objetos Paciente asociados con el objeto Consulta
     */
    public void loadPatientsData() {
        
        List<PatientDTO> patientsDTO = listener.getAllPatients();
            
        for(PatientDTO patientDTO: patientsDTO) {
            comboBoxPatients.addItem(patientDTO);
        }
        
        comboBoxPatients.clearSelectedItems();
        
    }
    
    public List<String> getSelectedPatientsId() {
        return comboBoxPatients.getSelectedItems()
                .stream()
                .map(item -> ((PatientDTO) item).getPatientDTOId()) 
                .toList();
    }
        
    /**  
     * Elige la accion a realizar por el objeto jButtonAddPatients
     */
    private void saveAction() {
        listener.updateConsultationPatientsDTO(getSelectedPatientsId());
        operationSuccess = true;
        dispose(); 
    }
    
    /**  
     * Elige la accion a realizar por el objeto jButtonCancel
     */
    private void cancelAction() {
        operationSuccess = false;
        dispose();
    }
    
    /**  
     * Llama al diálogo y bloquea hasta que se cierre.  
     * @param listener
     * @return true si el guardado fue exitoso, false si canceló o hubo error.  
     */
    public static boolean showDialog(IConsultationPatientsDialog listener) {
        Frame ownerFrame = JOptionPane.getFrameForComponent((Component) listener);
        ConsultationPatientsDialog dialog = new ConsultationPatientsDialog(ownerFrame, listener, true);
        dialog.setVisible(true);  
        
        return dialog.operationSuccess;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonAddPatients = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        comboBoxPatients = new com.application.utils.ComboBoxMultiSelection();
        jButtonClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Pacientes");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(700, 50));

        jButtonAddPatients.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jButtonAddPatients.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButtonAddPatients.setText("Agregar pacientes");
        jButtonAddPatients.setMaximumSize(new java.awt.Dimension(200, 30));
        jButtonAddPatients.setMinimumSize(new java.awt.Dimension(200, 30));
        jButtonAddPatients.setPreferredSize(new java.awt.Dimension(200, 30));
        jButtonAddPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPatientsActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButtonCancel.setText("Cancelar");
        jButtonCancel.setToolTipText("");
        jButtonCancel.setMaximumSize(new java.awt.Dimension(150, 30));
        jButtonCancel.setMinimumSize(new java.awt.Dimension(150, 30));
        jButtonCancel.setPreferredSize(new java.awt.Dimension(150, 30));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddPatients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        comboBoxPatients.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        comboBoxPatients.setMaximumSize(new java.awt.Dimension(400, 30));
        comboBoxPatients.setMinimumSize(new java.awt.Dimension(400, 30));
        comboBoxPatients.setPreferredSize(new java.awt.Dimension(400, 30));

        jButtonClean.setText("Limpiar");
        jButtonClean.setToolTipText("");
        jButtonClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboBoxPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonClean, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBoxPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonClean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        cancelAction();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonAddPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPatientsActionPerformed
        saveAction();
    }//GEN-LAST:event_jButtonAddPatientsActionPerformed

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
        comboBoxPatients.clearSelectedItems();
    }//GEN-LAST:event_jButtonCleanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.application.utils.ComboBoxMultiSelection comboBoxPatients;
    private javax.swing.JButton jButtonAddPatients;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
